FROM linuxbrew/linuxbrew
MAINTAINER Shaun Jackman <sjackman@gmail.com>

ENV PERL5LIB /home/linuxbrew/perl5/lib/perl5
RUN brew install cpanm
# For edirect
RUN cpanm HTML::Entities LWP::Simple LWP::Protocol::https

RUN brew tap homebrew/science
RUN brew install a5
RUN brew install abacas
RUN brew install abyss-explorer
RUN brew install abyss
RUN brew install ace-corrector
RUN brew install adam
# RUN brew install adapterremoval
RUN brew install afra
RUN brew install allpaths-lg
# RUN brew install amos
RUN brew install analysis
RUN brew install andi
# RUN brew install anvio
RUN brew install arcs
RUN brew install art
RUN brew install artemis
RUN brew install astral
RUN brew install atram
# RUN brew install augustus
RUN brew install bam-readcount
RUN brew install bamhash
RUN brew install bamm
RUN brew install bamtools
RUN brew install bamutil
RUN brew install barrnap
RUN brew install bbtools
RUN brew install bcalm
RUN brew install bcftools
RUN brew install beagle
RUN brew install beast
RUN brew install beast2
RUN brew install bedops
RUN brew install bedtools
RUN brew install beetl
RUN brew install bfc
RUN brew install bioawk
RUN brew install biobloomtools
RUN brew install biointerchange
RUN brew install biomake
# RUN brew install biopieces
RUN brew install blasr
RUN brew install blast
# RUN brew install blat
# RUN brew install bless
RUN brew install bowtie
RUN brew install bowtie2
RUN brew install bpipe
RUN brew install breseq
RUN brew install busco
RUN brew install bwa
RUN brew install canu
RUN brew install cap3
RUN brew install cd-hit
# RUN brew install cegma
RUN brew install celera-assembler
RUN brew install centrifuge
RUN brew install cerulean
RUN brew install circlator
RUN brew install clark
RUN brew install clonalframeml
RUN brew install clonehd
RUN brew install clustal-omega
RUN brew install clustal-w
# RUN brew install corset
RUN brew install cytoscape
RUN brew install daligner
RUN brew install dazz_db
# RUN brew install delly
RUN brew install dextractor
RUN brew install diamond
RUN brew install dida
RUN brew install discovar
# RUN brew install discovardenovo
RUN brew install dsk
RUN brew install dwgsim
RUN brew install e-mem
RUN brew install edirect
# RUN brew install ensembl-tools
RUN brew install exonerate
RUN brew install express
RUN brew install fasta
RUN brew install fastml
RUN brew install fastq-tools
RUN brew install fastqc
RUN brew install fasttree
RUN brew install fastuniq
RUN brew install fastx_toolkit
RUN brew install fermi-lite
RUN brew install fermi
RUN brew install fermi2
RUN brew install fermikit
RUN brew install flash
RUN brew install freebayes
RUN brew install freec
RUN brew install fsa
RUN brew install fwdpp
# RUN brew install gaemr
# RUN brew install garli
RUN brew install gatb
# RUN brew install gatk
RUN brew install geneid
# RUN brew install genewise
# RUN brew install genometools
RUN brew install gingr
RUN brew install glimmerhmm
# RUN brew install gmap-gsnap
RUN brew install grabix
# RUN brew install graphlan
RUN brew install gubbins
# RUN brew install harvest-tools
RUN brew install hisat
RUN brew install hisat2
RUN brew install hlaminer
RUN brew install hmmer
RUN brew install hmmer2
RUN brew install htsbox
RUN brew install htslib
RUN brew install humann2
RUN brew install idba
RUN brew install igv
RUN brew install igvtools
RUN brew install impute2
RUN brew install infernal
RUN brew install iqtree
# RUN brew install iva
RUN brew install jellyfish-1.1
RUN brew install jellyfish
RUN brew install kaiju
RUN brew install kallisto
RUN brew install kat
RUN brew install kent-tools
RUN brew install kmacs
RUN brew install kmc
RUN brew install kmergenie
RUN brew install kmerstream
RUN brew install kollector
# RUN brew install kraken
RUN brew install last
RUN brew install libbigwig
RUN brew install libpll
RUN brew install libsequence
RUN brew install links-scaffolder
RUN brew install lobstr
RUN brew install lsd
RUN brew install lumpy-sv
RUN brew install macse
RUN brew install mafft
# RUN brew install maker
RUN brew install mapsembler2
RUN brew install maq
RUN brew install mash
RUN brew install masurca
RUN brew install mcl
RUN brew install megahit
# RUN brew install meme
# RUN brew install metaphlan
RUN brew install mhap
RUN brew install minced
RUN brew install minia
RUN brew install miniasm
RUN brew install minimap
RUN brew install mir-prefer
# RUN brew install mira
RUN brew install mitofy
# RUN brew install mlst
# RUN brew install mothur
RUN brew install mrbayes
RUN brew install multi-worm-tracker
RUN brew install mummer
RUN brew install muscle
RUN brew install nanopolish
# RUN brew install ncbi-c++-toolkit
RUN brew install ncl
RUN brew install newick-utils
RUN brew install newicktools
RUN brew install nextflow
RUN brew install nonpareil
RUN brew install novoalign
RUN brew install ntcard
RUN brew install nxtrim
RUN brew install oases
# RUN brew install ogdraw
RUN brew install oma
RUN brew install orthofinder
RUN brew install paml
RUN brew install pandaseq
RUN brew install parsnp
RUN brew install pathd8
RUN brew install pathvisio
RUN brew install pbsuite
RUN brew install pear
RUN brew install phipack
RUN brew install phlawd
RUN brew install phylip
RUN brew install phyml
RUN brew install phyx
RUN brew install picard-tools
RUN brew install piler
RUN brew install pilercr
RUN brew install pilon
RUN brew install plink
# RUN brew install plink2
RUN brew install poa
# RUN brew install populations
# RUN brew install poretools
RUN brew install prodigal
# RUN brew install prokka
RUN brew install proteinortho
RUN brew install psmc
# RUN brew install quaff
# RUN brew install quake
RUN brew install quast
RUN brew install quest
RUN brew install quorum
RUN brew install racon
# RUN brew install rampart
RUN brew install rapsearch2
RUN brew install raxml
# RUN brew install ray
RUN brew install rcorrector
RUN brew install readseq
RUN brew install readsim
# RUN brew install reapr
RUN brew install recon
RUN brew install repeatmasker
RUN brew install repeatmodeler
RUN brew install repeatscout
RUN brew install rmblast
RUN brew install rna-star
RUN brew install rnammer
RUN brew install ropebwt2
RUN brew install sailfish
RUN brew install salmon
RUN brew install sambamba
RUN brew install samblaster
RUN brew install samtools-0.1
RUN brew install samtools
RUN brew install scarpa
RUN brew install sdsl-lite
RUN brew install seqan
RUN brew install seqtk
RUN brew install sequel
RUN brew install sga
RUN brew install shrimp
# RUN brew install simulate-pcr
RUN brew install skewer
RUN brew install smalt
RUN brew install smrtanalysis
RUN brew install snap-aligner
RUN brew install snap
RUN brew install snoscan
RUN brew install snp-sites
RUN brew install snpeff
RUN brew install soapdenovo
# RUN brew install sortmerna
RUN brew install spaced
RUN brew install spades
RUN brew install spici
RUN brew install squeezambler
RUN brew install sratoolkit
RUN brew install ssake
RUN brew install stringtie
RUN brew install swarm
RUN brew install tagdust
RUN brew install tasr
RUN brew install tbl2asn
RUN brew install tophat
RUN brew install trans-abyss
# RUN brew install trans_proteomic_pipeline
RUN brew install transdecoder
RUN brew install transrate-tools
RUN brew install trf
RUN brew install trimadap
RUN brew install trimal
RUN brew install trimmomatic
RUN brew install trinity
RUN brew install trnascan
# RUN brew install ucsc-genome-browser
RUN brew install uproc
RUN brew install vague
RUN brew install varscan
RUN brew install vcake
RUN brew install vcflib
RUN brew install vcftools
RUN brew install velvet
RUN brew install viennarna
RUN brew install vsearch
RUN brew install vt
RUN brew install weblogo
RUN brew install wiggletools
RUN brew install yaha
