FROM sjackman/linuxbrew
MAINTAINER Shaun Jackman <sjackman@gmail.com>

RUN brew tap homebrew/science
#RUN brew install a5
RUN brew install abyss
RUN brew install idba
RUN brew install megahit
#RUN brew install meraculous
RUN brew install minia
RUN brew install quast
RUN brew install rampart
RUN brew install sga
RUN brew install soapdenovo
RUN brew install spades
#RUN brew install sparseassembler
#RUN brew install squeezambler
RUN brew install velvet
RUN brew install velvetoptimiser
